---
title: "EDA Week 7 Code Portfolio — Hanzhi He"
author: "HANZHI"
date: "7/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

This is one of the R Markdown documents for Hanzhi's code portfolio from Week 7 to 12. 

Week 7 -- data visualization for Data Science:

```{r tidyverse}
#This chapter focuses on ggplot2. Since I have already installed package #tidyverse, I only need to load it. Otherwise I need to run

#install.packages("tidyverse")

library(tidyverse)
mpg
#simple plot to get an idea of ggplot
ggplot(data = mpg)
#plot scatter plot to see the relation between displ and hwy.
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
#plot scatter plot to see the relation between hwy and cyl.
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = cyl, y = hwy))
#plot scatter plot to see the relation between class and drv.
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = class, y = drv))
#the plot of class and drv doesn't make much sense cuz there's no linear relationship between them.

#add aesthetic to scatter plot
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))

#set aesthetic manually
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), col = "red")

#plot scatter plots with facets seperated by classes
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, col = "red")) + 
  facet_wrap(~ class, nrow = 2)

#plot scatter plots with facets seperated by values from two variables
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)

# Change geom from scatter to smooth
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))

# Add linetype
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))

# How to place multiple geoms in the same plot
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
              
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
    
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE
  )

# How to prevent duplications in codes
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()

#To display different aes, only add aes to the specific geom
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = class)) + geom_smooth()


#To display specific data for geom smooth 
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)


#Plot a bar chart
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))

#Plot statistical summary using ggplot
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )

#Color a bar chart using col or fill
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, colour = cut))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))

#Fill applied to another variable gives stacked bars as output
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))

#To see overlaps of stacked bars, turn alpha to a small number or set it transparent use fill = NA
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity")

# Use position="fill" to plot bars with the same height for better illustration and comparison
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")

# Use position="fill" to plot overlapping stocks next to each other to make it easier for value comparison of different objects
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")

# Use coord_flip() to switch x and y axis in a plot, and can change boxplots to horizontal, or make long labels look better without overlapping on the x axis.

ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot()
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot() +
  coord_flip()

# Use coord_quickmap() to correct maps when plotting spatial data with ggplot
install.packages("maps")
nz <- map_data("nz")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black") +
  coord_quickmap()

#Use coord_polar() to plot on polar coordinates
bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar()


```

